backend:
  name: github
  repo: jeremy-london/docker-pi # Change this to your repo
  branch: test

production:
  backend:
    name: github
    repo: jeremy-london/docker-pi # Change this to your repo
    branch: master

media_folder: static/img
public_folder: /img

display_url: docker-pi.com

# publish_mode: editorial_workflow

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'src/posts'
    create: true
    sort: 'date:desc'
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }
